### PR TITLE
Make "Your Options" pane sticky.

### PR DESCRIPTION
**Pull request by ancker010**
Per our discussion in the issues, this PR includes a CSS class 'div.sticky' which is applied to the "Your Options" element on the main page.

The "Your Options" element now floats (is sticky) in its position when the page is scrolled.

### CODE REVIEW

**Comment by vsoch** [comment]
This looks great! Do you know why it didn't seem to influence mobile? I'll try again in the browser now.

**Comment by ancker010** [comment]
Your CSS has logic for screens smaller than NNN pixels. In that case the rows are stacked instead of columns. (At least I think so, if I make my desktop browser window super small, the "Your Options" section jumps to the bottom just like on mobile.)

**Comment by vsoch** [comment]
I wonder if bootstrap columns consider the "top" of the screen on mobile to be directly under the previous column? It doesn't seem to be an issue on iOS, not sure about android.

**Comment by vsoch** [comment]
Anyway, I'm good with the changes - I think things are better (for most) than before, and we can always address some future issue if someone brings it up / finds one. Merging!

**Pull request merged**
